[build]
  command = "bash ./netlify-build.sh"
  publish = "apps/frontend/.next"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"
  RUSTUP_HOME = "/opt/buildhome/.rustup"
  CARGO_HOME = "/opt/buildhome/.cargo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
