[build]
  base = "apps/frontend"
  command = "npm install && npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD --quiet apps/backend/ || echo 'Backend changes detected but will be ignored in this build.'"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  
  # Frontend environment variables
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"

# Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Explicitly disable Python
[build.environment]
  PYTHON = "/bin/false"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

# Ignore backend directory
[[redirects]]
  from = "/backend/*"
  to = "/404.html"
  status = 404
