[build]
  base = "apps/frontend"
  command = "npm ci --include=dev && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD --quiet apps/backend/ || echo 'Backend changes detected but will be ignored in this build.'"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
  PYTHON = "/bin/false"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

# Redirects configuration
[[redirects]]
  from = "/backend/*"
  to = "/404.html"
  status = 404

# Disable default plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  enabled = false

[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false

# Explicitly enable Vite plugin if needed
# [[plugins]]
#   package = "@netlify/plugin-vite"
#   enabled = true
