[build]
  base = "apps/frontend"
  command = "npm ci --include=dev && npm run build"
  publish = "dist"  # Vite outputs to 'dist' directory
  ignore = "git diff --quiet HEAD^ HEAD --quiet apps/backend/ || echo 'Backend changes detected but will be ignored in this build.'"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "${NEXT_PUBLIC_API_URL}"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
  PYTHON = "/bin/false"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

# Optional: Keep Lighthouse if you want to use it
[[plugins]]
package = "@netlify/plugin-lighthouse"

# Redirects configuration
[[redirects]]
from = "/backend/*"
to = "/404.html"
status = 404
