[build]
  base = "apps/frontend"  # Build from frontend directory
  publish = "apps/frontend/dist"  # Publish from frontend's dist directory
  command = "cd apps/frontend && npm ci && npm run build"

[build.environment]
  VITE_BACKEND_URL = "https://api.astrobalendar.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://api.astrobalendar.onrender.com"
    Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Credentials = "true"
