[build]
  command = "cd apps/frontend && npm install && npm run build"
  publish = "apps/frontend/.next"
  base = "."

[build.environment]
  # Node.js configuration
  NODE_VERSION = "18"
  NODE_ENV = "production"
  
  # Application environment variables
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"

# Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
