[build]
  command = "cd apps/frontend && npm install && npm run build"
  publish = "apps/frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  PYTHON = ""
  
  # Frontend environment variables
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"

# Next.js plugin configuration (required for Next.js projects)
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Disable Python installation
    python = false
