[build]
  command = "bash ./netlify-build.sh"
  publish = "apps/frontend/.next"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"
  
# Disable Python installation
[build.environment]
  PYTHON_VERSION = ""
  PIPENV_RUNTIME = ""

# Disable automatic Python installation
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    python = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
