[build]
  base = "apps/frontend"
  command = "npm ci --include=dev && npm run build"
  publish = "dist"  # Vite outputs to 'dist' directory
  ignore = "git diff --quiet HEAD^ HEAD --quiet apps/backend/ || echo 'Backend changes detected but will be ignored in this build.'"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_URL = "${VITE_API_URL}"
  VITE_GOOGLE_MAPS_API_KEY = "${VITE_GOOGLE_MAPS_API_KEY}"
  PYTHON = "/bin/false"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[redirects]]
from = "/backend/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"

[[headers]]
for = "/assets/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
