# Render Blueprint for Astrobalendar
# Docs: https://render.com/docs/blueprint-spec

services:
  # Backend: Python FastAPI Server
  - type: web
    name: astrobalendar-backend
    env: python
    plan: free
    region: oregon
    
    # Build & Start Commands
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd apps/backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    
    # Environment Variables
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src/apps/backend
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: ALLOWED_ORIGINS
        value: https://astrobalendar.netlify.app,https://astrobalendar.com
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: astrobalendar-db
          property: connectionString
    
    # Health Check Path
    healthCheckPath: /health
    
    # Auto-Deploy from main branch
    autoDeploy: true
    
    # IP Allow List (restrict access if needed)
    # ipAllowList: 
    #   - 192.0.2.0/24
    #   - 203.0.113.0/24
    
    # Scaling
    scaling:
      maxInstances: 1
      minInstances: 1
      targetCPUUtilizationPercent: 70

# Database (MongoDB)
databases:
  - name: astrobalendar-db
    plan: free
    databaseName: astrobalendar
    user: astrobalendar_user
    ipAllowList:
      - 0.0.0.0/0  # Warning: This allows access from any IP. Restrict in production.

# Cron Jobs (uncomment and configure as needed)
# jobs:
#   - name: update-daily-horoscopes
#     type: cron
#     schedule: "0 0 * * *"  # Run daily at midnight
#     command: >
#       cd apps/backend &&
#       poetry run python -m scripts.update_horoscopes
#     envVars:
#       - key: ENVIRONMENT
#         value: production
#     plan: free

  # 🗄️ Database: MongoDB (Using Render's Managed MongoDB)
  - type: mongodb
    name: astrobalendar-db
    plan: free
    databaseName: astrobalendar
    ipWhitelist: []  # Will be auto-populated by Render
