# Render Configuration for Astrobalendar Backend
# Docs: https://render.com/docs/deploy-python

services:
  # 🔧 Backend: Python FastAPI Server
  - type: web
    name: astrobalendar-backend
    env: python3
    plan: free
    region: oregon
    
    # Build & Start Commands
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    
    # Environment Variables
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src/apps/backend
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: ALLOWED_ORIGINS
        value: https://astrobalendar.netlify.app,https://astrobalendar.com
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: astrobalendar-db
          property: connectionString
    
    # Scaling
    scaling:
      maxInstances: 1
      minInstances: 1
      targetCPUUtilizationPercent: 70
    
    # Add-ons (uncomment and configure as needed)
    # addOns:
    #   - name: astrobalendar-redis
    #     type: redis
    #     plan: free
    #     options:
    #       version: 6
    
    # Custom domains (configure in Render dashboard)
    # customDomains:
    #   - name: api.astrobalendar.com
    #     domainType: apex
    #     redirectWww: true
    autoDeploy: true
    
  # 🗄️ Database: MongoDB (Using Render's Managed MongoDB)
  - type: mongodb
    name: astrobalendar-db
    plan: free
    databaseName: astrobalendar
    ipWhitelist: []  # Will be auto-populated by Render
