# Render Blueprint for Astrobalendar
# Docs: https://render.com/docs/blueprint-spec

services:
  # Backend Service
  - type: web
    name: astrobalendar-backend
    region: oregon
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r apps/backend/requirements.txt
      cd apps/backend && pip install -r requirements.txt
    startCommand: >-
      gunicorn apps.backend.main:app 
      --workers 4 
      --worker-class uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      # Firebase Configuration (set in Render dashboard)
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_MEASUREMENT_ID
        sync: false
      # Redis Configuration
      - key: REDIS_URL
        fromService:
          type: redis
          name: astrobalendar-redis
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    scaling:
      maxInstances: 1
      minInstances: 1
      concurrency: 1

  # Redis Service
  - type: redis
    name: astrobalendar-redis
    plan: free
    ipAllowList: []

# Environment Variables (for development)
# Note: These are just for reference, set them in Render dashboard
# PYTHONUNBUFFERED=1
# PYTHONDONTWRITEBYTECODE=1

# Cron Jobs (uncomment and configure as needed)
# jobs:
#   - name: update-daily-horoscopes
#     type: cron
#     schedule: "0 0 * * *"  # Run daily at midnight
#     command: >
#       cd apps/backend &&
#       python -m scripts.update_horoscopes
#     envVars:
#       - key: ENVIRONMENT
#         value: production
#     plan: free
