services:
  backend:
    type: web
    env: production
    buildCommand: docker build -t astrobalendar-backend ./apps/backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URI
        value: "mongodb://mongodb:27017/astrobalendar"
      - key: WINDSURF_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: CORS_ALLOW_ORIGINS
        value: "https://astrobalendar.netlify.app"
      - key: SECRET_KEY
        value: "your-secret-key-here"
      - key: JWT_SECRET
        value: "your-jwt-secret-here"
      - key: RATE_LIMIT_WINDOW
        value: "60"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
    healthcheck:
      test: "curl -f http://localhost:8000/api/health"
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    type: mongodb
    env: production
    databaseName: astrobalendar
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: password
    healthcheck:
      test: "mongo --eval 'db.adminCommand("ping")'"
      interval: 30s
      timeout: 10s
      retries: 3

# Security Settings
security:
  https_only: true
  domain_verification: true
  rate_limiting:
    enabled: true
    window: 60
    max_requests: 100
  cors:
    enabled: true
    allowed_origins:
      - "https://astrobalendar.netlify.app"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
