version: 1

# Global deployment settings
windsurf:
  name: AstroBalendar
  region: auto  # Will be set by Windsurf based on availability
  environment: production
  domain: astrobalendar  # Will be used to generate the subdomain

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "80:4173"  # Map to port 80 for public access
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - WINDSURF_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

environment:
  production:
    VITE_BACKEND_URL: "https://api.astrobalendar.com"
    MONGO_URI: "mongodb://admin:password@mongodb:27017/astrobalendar"
    NODE_ENV: production
    WINDSURF_ENV: production

  development:
    VITE_BACKEND_URL: "http://localhost:8000"
    MONGO_URI: "mongodb://localhost:27017/astrobalendar"
    NODE_ENV: development
    WINDSURF_ENV: development
