[build]
base = "apps/frontend"
command = "npm run build"
publish = "dist"

[build.environment]
VITE_API_URL = "https://astrobalendar-backend.onrender.com"
NODE_VERSION = "18"



[[redirects]]
from = "/*"
to = "/index.html"
status = 200






