[build]
  command = "npm install && npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  
  # Disable Python installation
  PYTHON_VERSION = ""
  
  # Application environment variables
  NEXT_PUBLIC_API_URL = "https://astrobalendar-backend.onrender.com"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    python = false

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
