# Netlify Configuration for Astrobalendar Frontend
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  base = "apps/frontend"
  command = "npm install && npm run build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep \"\[skip-netlify\""

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build environment
  NODE_ENV = "production"
  
  # Backend API URL - will be overridden by Netlify environment variables
  VITE_BACKEND_URL = "https://astrobalendar-backend.onrender.com"
  
  # Google Maps API Key - set in Netlify dashboard
  VITE_GOOGLE_MAPS_API_KEY = "@google_maps_api_key"
  
  # Build optimization
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.onrender.com https://*.netlify.app;"
    
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm install --production=false && npm run build"

[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "staging" }

# Redirect all SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://maps.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: http:;
      font-src 'self' https://fonts.gstatic.com data:;
      connect-src 'self' https://*.googleapis.com https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.firebaseio.com https://*.firebase.com https://*.render.com;
      frame-src 'self' https://www.google.com https://www.youtube.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
    """.replace(/\s+/g, ' ').trim()

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable Gzip and Brotli compression
[[plugins]]
  package = "@netlify/plugin-gzip"

# Enable Sitemap generation
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    output = "/sitemap.xml"
    exclude = ["/admin/*", "/api/*"]

# Environment variables that need to be set in Netlify dashboard:
# - VITE_FIREBASE_API_KEY
# - VITE_FIREBASE_AUTH_DOMAIN
# - VITE_FIREBASE_PROJECT_ID
# - VITE_FIREBASE_STORAGE_BUCKET
# - VITE_FIREBASE_MESSAGING_SENDER_ID
# - VITE_FIREBASE_APP_ID
# - VITE_GOOGLE_MAPS_API_KEY






