[build]
  base = ""
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://api.astrobalendar.com"  # Replace with your actual API URL

[context.production]
  command = "npm run build"
  publish = "dist"
