services:
  - type: web
    name: astrobalendar-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >-
      python -c "import sys; print('Python version:', sys.version)" &&
      python -c "import pkg_resources; installed = pkg_resources.working_set; installed_packages = sorted(['%s==%s' % (i.key, i.version) for i in installed]); print('Installed packages:', installed_packages)" &&
      PYTHONPATH=/opt/render/project/src uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: ALLOWED_ORIGINS
        value: https://astrobalendar.netlify.app,https://astrobalendar.com
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: astrobalendar-db
          property: connectionString
    scaling:
      maxInstances: 1
      minInstances: 1
      instanceSize: free
