[build]
  base = "/apps/frontend"
  command = "npm run build"
  publish = "/apps/frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
