name: Backend CI (Render/Docker)

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f poetry.lock ]; then pip install poetry && poetry install; fi

      - name: Run tests
        working-directory: apps/backend
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest; fi

      # Optional: Deploy to Render (set RENDER_DEPLOY_HOOK in repo secrets)
      - name: Deploy to Render
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
