name: Deploy AstroBalendar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand("ping")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          cd apps/backend
          pip install -r requirements.txt

      # Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Node dependencies
      - name: Install Node dependencies
        run: |
          cd apps/frontend
          npm ci

      # Build frontend
      - name: Build frontend
        run: |
          cd apps/frontend
          npm run build

      # Run tests (if any)
      - name: Run tests
        run: |
          cd apps/backend
          pytest

      # Deploy to Windsurf
      - name: Deploy to Windsurf
        env:
          WINDSURF_API_KEY: ${{ secrets.WINDSURF_API_KEY }}
        run: |
          # Add your Windsurf deployment script here
          echo "Deploying to Windsurf..."
          # Example: windsurf deploy . --env production
